apiVersion: v1
kind: PersistentVolume
metadata:
  name: config-db-pv
  namespace: xconnected
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data/postgres  # Adjust path as needed
  storageClassName: manual