apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: config-db-pvc
  namespace: xconnected
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: manual
