apiVersion: v1
kind: Service
metadata:
  name: courtcase-app
  namespace: xconnected
  labels:
    app: courtcase-app
spec:
  ports:
  - port: 4205
    targetPort: 4205
  selector:
    app: courtcase-app
  type: ClusterIP