apiVersion: apps/v1
kind: Deployment
metadata:
  name: courtcase-app
  namespace: xconnected
  labels:
    app: courtcase-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: courtcase-app
  template:
    metadata:
      labels:
        app: courtcase-app
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
      - name: courtcase-app
        image: xconnected/components:courtcases-app-3.0
        #imagePullPolicy: Always
        ports:
        - containerPort: 4205