apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongodb-pv
  namespace: xconnected
spec:
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data/mongodb  # Adjust path as needed
  storageClassName: manual

