apiVersion: v1
kind: Service
metadata:
  name: mongodb
  namespace: xconnected
spec:
  ports:
  - port: 27017
    targetPort: 27017
  selector:
    app: mongodb
  type: ClusterIP  # Use NodePort or LoadBalancer if you want external access
