
volumes:
  postgres-keycloak:
      driver: local

services:
  postgres:
    image: postgres
    volumes:
      - postgres-keycloak:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password

  keycloak:
    image: quay.io/keycloak/keycloak:24.0.3
    volumes:
      - ./keycloak/xconnected/themes:/opt/keycloak/themes
      # - ./providers:/opt/keycloak/providers
      - ./keycloak/certs/:/etc/x509/https/
      - ./keycloak/vault:/opt/vault/
    command: start
    environment:
      KC_DB: postgres
      KC_METRICS_ENABLED: 'true'
      KC_DB_URL_HOST: postgres
      KC_DB_URL_DATABASE: keycloak
      KC_DB_URL_PORT: 5432
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: password
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: Pa55w0rd
      PROXY_ADDRESS_FORWARDING: 'true'
      KC_HEALTH_ENABLED: 'true'
      KC_HOSTNAME_STRICT: 'false'
      KC_HTTP_ENABLED: 'true'
      KC_HTTP_HOST: 0.0.0.0
      KC_HTTPS_CERTIFICATE_FILE: /etc/x509/https/keycloak.crt
      KC_HTTPS_CERTIFICATE_KEY_FILE: /etc/x509/https/keycloak.key
      KC_VAULT: file
      KC_VAULT_DIR: /opt/vault/
      KC_VAULT_PASS: admin123
      KC_HTTP_RELATIVE_PATH: /auth
      KC_SPI_THEME_ACCOUNT_THEME: xconnected
      KC_SPI_THEME_LOGIN_THEME: xconnected
      KC_SPI_THEME_ADMIN_THEME: xconnected
      KC_TRANSACTION_XA_ENABLED: 'true'
      KC_TRANSACTION_MANAGER_ENABLE_RECOVERY: 'true'
      QUARKUS_TRANSACTION_MANAGER_ENABLE_RECOVERY: 'true'
      KC_CACHE: ispn
      KC_CACHE_STACK: udp  
      JDBC_PARAMS: "ssl=true"
    ports:
      # - 8080:8080
      - 8443:8443
    depends_on:
      - postgres
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.keycloak.rule=PathPrefix(`/auth`)"
      - "traefik.http.services.keycloak.loadbalancer.server.port=8080"