services:
  itms-app:
    image: xconnected/components:itms-app-2.0
    restart: on-failure
    expose:
      - '4201'
    # ports:
    #   - "4201:4201"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.itms.rule=PathPrefix(`/itms`)"
      - "traefik.http.services.itms.loadbalancer.server.port=4201"

  config-app:
    image: xconnected/components:conf-app-2.0
    restart: on-failure
    expose:
      - '4202'
    # ports:
    #   - "4202:4202"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.conf.rule=PathPrefix(`/conf`)"
      - "traefik.http.services.conf.loadbalancer.server.port=4202"


  home-app:
    image: xconnected/components:home-app-2.0
    restart: on-failure
    expose:
      - '4200'
    # ports:
    #   - "4200:4200"
    volumes:
     - ./ui/home/assets/environment.json:/usr/share/nginx/html/assets/environment.json
     - ./ui/home/assets/federation.manifest.json:/usr/share/nginx/html/assets/federation.manifest.json
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.home.rule=PathPrefix(`/`)"
      - "traefik.http.services.home.loadbalancer.server.port=4200"