apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: xconnected
data:
  prometheus.yml: |
    global:
      scrape_interval: 60s

    scrape_configs:
      - job_name: 'prometheus'
        static_configs:
          - targets: ['prometheus.xconnected.svc:9090']

      - job_name: 'node-exporter'
        static_configs:
          - targets: ['node-exporter.xconnected.svc.cluster.local:9100']

      - job_name: 'postgres-exporter'
        static_configs:
          - targets: ['postgres-exporter.xconnected.svc.cluster.local:9187']
  
      - job_name: 'k3s-metrics'
        scheme: https
        tls_config:
          ca_file: "/var/run/secrets/kubernetes.io/serviceaccount/ca.crt"
        authorization:
          credentials_file: "/var/run/secrets/kubernetes.io/serviceaccount/token"
        static_configs:
          - targets: ['192.168.29.194:10250']
      
      - job_name: 'kube-state-metrics'
        static_configs:
          - targets: ['kube-state-metrics.xconnected.svc.cluster.local:8080']

      - job_name: 'cadvisor'
        static_configs:
          - targets: ['cadvisor.xconnected.svc.cluster.local:8081']
      
      - job_name: 'mongodb-exporter'
        static_configs:
          - targets:
              - 'mongodb-exporter.xconnected.svc.cluster.local:9216'
      
      - job_name: 'keycloak-exporter'
        metrics_path: '/auth/metrics'
        static_configs:
          - targets: ['keycloak.xconnected.svc.cluster.local:8080']

      - job_name: minio-job
        bearer_token: eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJwcm9tZXRoZXVzIiwic3ViIjoiTW5pMm1TVDhKZWZsNnFuWmtFRmwiLCJleHAiOjQ4OTYwNzk2OTZ9.kHuvw0tp19pbvwGoetdC-Qz2im-UkgwBlt34idjdTCS8ProXH7Mtwc6PJXxZifdvC92w5ez1KXtMcj4fMl3BCA
        metrics_path: /minio/v2/metrics/cluster
        scheme: http
        static_configs:
          - targets: ['10.72.5.6:9000']