apiVersion: apps/v1
kind: Deployment
metadata:
  name: minio-deployment
  namespace: xconnected
spec:
  replicas: 1
  selector:
    matchLabels:
      app: minio
  template:
    metadata:
      labels:
        app: minio
    spec:
      containers:
      - name: minio
        image: quay.io/minio/minio:latest
        args:
          - server
          - --console-address
          - ":9001"
          - /data
        ports:
        - containerPort: 9000
        - containerPort: 9001
        env:
        - name: MINIO_ROOT_USER
          value: "dinkar"
        - name: MINIO_ROOT_PASSWORD
          value: "Strong#Pass#2022"
        volumeMounts:
        - name: minio-storage
          mountPath: /data
      volumes:
      - name: minio-storage
        persistentVolumeClaim:
          claimName: minio-pvc  # this comes from pvc claim # mentioned in pvc.yml