apiVersion: v1
kind: PersistentVolume
metadata:
  name: minio-pv
  namespace: xconnected
spec:
  capacity:
    storage: 50Ti
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data # path form the physical disk 
    
