apiVersion: v1
kind: PersistentVolume
metadata:
  name: minio-pv
  namespace: xconnected
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data/minio # path form the physical disk 
    