apiVersion: v1
kind: PersistentVolume
metadata:
  name: conf-api-pv
  namespace: xconnected
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  hostPath:
    path: "/data/conf-api"