apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: conf-api-pvc
  namespace: xconnected
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
